from . import custom_link
from . import product_template
from . import pos_order
from . import pos_order_line
from . import business_type
from . import res_partner
from . import pos_config
from . import pos_payment
from . import pos_payment_method
